# models/sources.yml
version: 2
sources:
  - name: football_raw # A name to reference the source
    catalog: learning_catalog
    schema: football_raw # The schema where the diamonds table is
    tables:
      - name: raw_appearances # The name of the table itself